name: Build Targets

on:
    push:
        paths-ignore:
            - '.gitignore'
            - 'LICENSE'
            - 'README.md'
    pull_request:
        paths-ignore:
            - '.gitignore'
            - 'LICENSE'
            - 'README.md'

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]

        runs-on: ${{ matrix.os }}

        steps:
        - uses: actions/checkout@v4
          name: Checkout

        - uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest
          name: Setup XMake

        - name: Build Debug
          run: |
            xmake f -m debug -y -v
            xmake

        - name: Build Release
          run: |
            xmake f -m release -y -v
            xmake

        - name: Prepare Linux artifacts
          if: startsWith(matrix.os, 'ubuntu')
          run: |
            mkdir linux-debug-artifact
            move build/debug-linux-x64/ProjectName/bin/ProjectName linux-debug-artifact/

            mkdir linux-release-artifact
            move build/release-linux-x64/ProjectName/bin/ProjectName linux-release-artifact/
            

        - name: Prepare MacOS artifacts
          if: startsWith(matrix.os, 'macos')
          run: |
            mkdir macos-debug-artifact
            move build/debug-macos-x64/ProjectName/bin/ProjectName macos-debug-artifact/

            mkdir macos-release-artifact
            move build/release-macos-x64/ProjectName/bin/ProjectName macos-release-artifact/


        - name: Prepare Windows artifacts
          if: startsWith(matrix.os, 'windows')
          run: |
            mkdir windows-debug-artifact
            move build/debug-windows-x64/ProjectName/bin/ProjectName.exe windows-debug-artifact/
            move build/debug-windows-x64/ProjectName/bin/ProjectName.pdb windows-debug-artifact/

            mkdir windows-release-artifact
            move build/release-windows-x64/ProjectName/bin/ProjectName.exe windows-release-artifact/


        - uses: actions/upload-artifacts@v3
          with:
            name: linux-debug-${{ github.run_id }}
            path: linux-debug-artifact/
          name: Upload Linux debug artifact

        - uses: actions/upload-artifacts@v3
          with:
            name: linux-release-${{ github.run_id }}
            path: linux-release-artifact/
          name: Upload Linux release artifact


        - uses: actions/upload-artifacts@v3
          with:
            name: macos-debug-${{ github.run_id }}
            path: macos-debug-artifact/
          name: Upload MacOS debug artifact

        - uses: actions/upload-artifacts@v3
          with:
            name: macos-release-${{ github.run_id }}
            path: macos-release-artifact/
          name: Upload MacOS release artifact

        
        - uses: actions/upload-artifacts@v3
          with:
            name: windows-debug-${{ github.run_id }}
            path: windows-debug-artifact/
          name: Upload Windows debug artifact

        - uses: actions/upload-artifacts@v3
          with:
            name: windows-release-${{ github.run_id }}
            path: windows-release-artifact/
          name: Upload Windows release artifact